### ISSUE TITLE
设置$AppClick auto track 后，view的点击事件会出现EXCEPTION

### ISSUE THREAD

**Issue by CharlesTai** [sensorsdata/sa-sdk-android#10]
集成的神策sdk是1.7.14版本，插件是1.0.9；
如果我只集成SDK  不应用插件的话，发现除了APPclick事件不能自动追踪外，其他功能都可以正常使用。
设置$AppClick auto track 后，view的点击事件会出现EXCEPTION
 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                   Process: com.ppdai.newarch, PID: 19610
                                                                   java.lang.NoSuchMethodError: com.sensorsdata.analytics.android.sdk.aop.ViewOnClickListenerAspectj.aspectOf
                                                                       at com.ppdai.newarch.activity.TitleActivity$1.onClick(TitleActivity.java:52)
                                                                       at android.view.View.performClick(View.java:4444)
                                                                       at android.view.View$PerformClick.run(View.java:18440)
                                                                       at android.os.Handler.handleCallback(Handler.java:733)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                       at android.os.Looper.loop(Looper.java:136)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5016)
                                                                       at java.lang.reflect.Method.invokeNative(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:515)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:795)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:611)
                                                                       at dalvik.system.NativeStart.main(Native Method)

**Comment by wangzhzh** [comment]
你们是哪个客户？
方便微信沟通吗？

**Comment by CharlesTai** [comment]
你好，

    我是拍拍贷的Android开发，微信号：13027167700



913882275@qq.com
 
发件人： wangzhzh
发送时间： 2017-08-02 15:13
收件人： sensorsdata/sa-sdk-android
抄送： CharlesTai; Author
主题： Re: [sensorsdata/sa-sdk-android] 设置$AppClick auto track 后，view的点击事件会出现EXCEPTION (#10)
你们是哪个客户？
方便微信沟通吗？

**Comment by wangzhzh** [comment]
我们的工程师联系你了吗？

**Comment by CharlesTai** [comment]
并没有~

**Comment by wangzhzh** [comment]
你现在的问题解决了吗？
下午你们的同事说你的问题解决了

**Comment by CharlesTai** [comment]
是解决了，只是想了解一下具体的原因，神策的同事已经加我了，多谢。

**Comment by wangzhzh** [comment]
如果开启 buildCache，Android Studio 会把依赖的 jar 或 arr 缓存到本地，并且把模块名称设置为 hash 值，导致 includeJarFilter 配置失效。
