### ISSUE TITLE
NoSuchMethodError No static method loadUrl2(Landroid/view/View;Ljava/lang/String;)

### ISSUE THREAD

**Issue by deng81416754** [sensorsdata/sa-sdk-android#113]
### 集成了Uni小程序SDK ，启用插件后`id("com.sensorsdata.analytics.android")` 打开小程序APP 就异常退出
停用插件后则正常
UniMP `https://nativesupport.dcloud.net.cn/UniMPDocs/SDKDownload/android`
环境：`com.sensorsdata.analytics.android:android-gradle-plugin2:3.5.0`
`kotlin 1.7.10 `
```
agp version[7.2.1]
gradle version[7.5.1] 
```
埋点 采用源码的方式依赖到项目

尝试了 排除报错类，依然报错
```
    sensorsAnalytics {
   com.sensorsdata.analytics.android.plugin.SensorsAnalyticsTransformHelper.special.add("io.dcloud.common.adapter.ui.AdaWebview")
    }
```

### 错误日志
```
    --------- beginning of crash
2022-10-19 17:24:20.988 11653-11653/com.zzz.zzz_super.debug E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.zzz.zzz_super.debug:unimp0, PID: 11653
    java.lang.NoSuchMethodError: No static method loadUrl2(Landroid/view/View;Ljava/lang/String;)V in class Lcom/sensorsdata/analytics/android/autotrack/aop/SensorsDataAutoTrackHelper; or its super classes (declaration of 'com.sensorsdata.analytics.android.autotrack.aop.SensorsDataAutoTrackHelper' appears in /data/data/com.zzz.zzz_super.debug/code_cache/.overlay/base.apk/classes2.dex)
        at io.dcloud.common.adapter.ui.AdaWebview$4.execute(Unknown Source:6)
        at io.dcloud.common.adapter.util.MessageHandler$1.handleMessage(Unknown Source:3)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:223)
        at android.app.ActivityThread.main(ActivityThread.java:7656)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:592)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:947)
```

希望得到 作者的回复 ，感谢

**Comment by dengshiwei** [comment]
@deng81416754 这个你得升级 SDK 版本到 6.5.0 以上

**Comment by deng81416754** [comment]
> @deng814167541.这个版本你得升级SDK版本到6.5.0以上，插件3.5.0以上，他俩配套使用；2. 或者你让一下插件的版本

clone 当前最新的工程 ， 复制进项目的。
看到git提交SDK版本最新为6.5.2
插件版本是  3.5.0

**Comment by dengshiwei** [comment]
@deng81416754 好的，目前内部在分析一下，应该是在 uni 上的一个 bug，会在近期的版本中修复，预计周五会发布修复版本

**Comment by deng81416754** [comment]
> @deng81416754 好的，目前内部在分析一下，应该是在 uni 上的一个 bug，会在近期的版本中修复，预计周五会发布修复版本

作者你好，  我升级了插件版本 ，问题解决了
```
    dependencies {
        classpath("com.sensorsdata.analytics.android:android-gradle-plugin2:3.5.1")
    }
```
