### ISSUE TITLE
调用SensorsDataAPI.getSuperProperties时偶发崩溃

### ISSUE THREAD

**Issue by qq549631030** [sensorsdata/sa-sdk-android#126]
sdk版本:6.6.8
                        Caused by: java.util.ConcurrentModificationException
                        	at java.util.LinkedHashMap$LinkedHashIterator.nextNode(LinkedHashMap.java:760)
                        	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:793)
                        	at java.util.LinkedHashMap$LinkedEntryIterator.next(LinkedHashMap.java:791)
                        	at org.json.JSONObject.writeTo(JSONObject.java:739)
                        	at org.json.JSONObject.toString(JSONObject.java:708)
                        	at com.sensorsdata.analytics.android.sdk.SensorsDataAPI.getSuperProperties(SensorsDataAPI.java:1323)

**Comment by dengshiwei** [comment]
@qq549631030 感谢反馈，内部会尽快修复。

**Comment by liuweiqiang2016** [comment]
v6.6.9 已修复，见：https://github.com/sensorsdata/sa-sdk-android/releases/tag/v6.6.9
