### ISSUE TITLE
Gradle 4.6+ android gradle Plugin 3.2 出现大量ArrayIndexOutOfBoundsException

### ISSUE THREAD

**Issue by SauceWu** [sensorsdata/sa-sdk-android#25]
####################################################################
####################################################################

java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException
java.lang.ArrayIndexOutOfBoundsException

**Comment by wangzhzh** [comment]
我们这几天也在测试 Gradle 4.6+ android gradle Plugin 3.2，暂未发现类似问题。
你那边有 demo 能复现这个问题吗？

**Comment by wangzhzh** [comment]
还有，使用我们的插件的版本号是多少？

**Comment by SauceWu** [comment]
还有几率导致崩溃 - -
 classpath 'com.sensorsdata.analytics.android:android-gradle-plugin2:2.1.0'
+
'com.sensorsdata.analytics.android:SensorsAnalyticsSDK:2.1.1'
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at XXApplication.initSensors()
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at XXApplication.onCreate(])
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1130)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at android.app.ActivityThread.handleBindApplication [XposedOriginal](ActivityThread.java:5965)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at de.robv.android.xposed.XposedBridge.invokeOriginalMethodNative(Native method)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at de.robv.android.xposed.XposedBridge.handleHookedMethod(XposedBridge.java:361)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at android.app.ActivityThread.handleBindApplication [XposedHooked](<Xposed>:-2)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at android.app.ActivityThread.-wrap1(ActivityThread.java:-1)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1755)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at android.os.Handler.dispatchMessage(Handler.java:106)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at android.os.Looper.loop(Looper.java:164)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at android.app.ActivityThread.main(ActivityThread.java:6753)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at java.lang.reflect.Method.invoke(Native method)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:482)
2018-09-30 16:05:07.540 19063-19076/? A/zygote64: runtime.cc:528]   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

**Comment by wangzhzh** [comment]
你是我们神策的客户吗？

**Comment by SauceWu** [comment]
是的啊。。之前用着都没问题 今天升级了之后才出的问题  崩溃也不是每次都有偶发性的

**Comment by wangzhzh** [comment]
你目前能联系到神策的技术支持工程师吗？我跟你私聊解决吧

**Comment by wangzhzh** [comment]
或者你告诉我你们是哪个公司？我们主动联系你们
