### ISSUE TITLE
自定义控件,空指针异常

### ISSUE THREAD

**Issue by CD3108** [sensorsdata/sa-sdk-android#34]
java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.String java.lang.CharSequence.toString()' on a null object reference
2019-05-21 17:26:38.091 26447-26447/cn.ninebot.ninebot W/System.err:     at com.sensorsdata.analytics.android.sdk.util.AopUtil.getViewText(AopUtil.java:244)
2019-05-21 17:26:38.091 26447-26447/cn.ninebot.ninebot W/System.err:     at com.sensorsdata.analytics.android.sdk.util.AopUtil.traverseView(AopUtil.java:174)
2019-05-21 17:26:38.091 26447-26447/cn.ninebot.ninebot W/System.err:     at com.sensorsdata.analytics.android.sdk.SensorsDataAutoTrackHelper.trackTabLayoutSelected(SensorsDataAutoTrackHelper.java:812)
2019-05-21 17:26:38.091 26447-26447/cn.ninebot.ninebot W/System.err:     at cn.ninebot.commonlibs.widget.TrackTabLayout$1.onTabSelected(TrackTabLayout.java:122)

**Comment by dengshiwei** [comment]
感谢反馈，正在验证

**Comment by dengshiwei** [comment]
版本 v3.1.4 已优化修复，感谢您的反馈。
