### ISSUE TITLE
使用 Kotlin 时 App 崩溃

### ISSUE THREAD

**Issue by loshine** [sensorsdata/sa-sdk-android#4]
给 RecyclerView 的 ViewHolder 的 itemView 设置 OnClickListener，当点击的时候程序崩溃。

```
05-18 03:29:32.641 2633-2633/cn.ztcjob.ztc E/AndroidRuntime: FATAL EXCEPTION: main
                                                             Process: cn.ztcjob.ztc, PID: 2633
                                                             java.lang.NoSuchMethodError: No static method aspectOf()Lcom/sensorsdata/analytics/android/sdk/aop/ViewOnClickListenerAspectj; in class Lcom/sensorsdata/analytics/android/sdk/aop/ViewOnClickListenerAspectj; or its super classes (declaration of 'com.sensorsdata.analytics.android.sdk.aop.ViewOnClickListenerAspectj' appears in /data/app/cn.ztcjob.ztc-2/base.apk)
                                                                 at cn.ztcjob.ztc.ui.business.home.BusinessHomeItemViewBinder$ViewHolder$bind$1.onClick(BusinessHomeItemViewBinder.kt:34)
                                                                 at android.view.View.performClick(View.java:5637)
                                                                 at android.view.View$PerformClick.run(View.java:22429)
                                                                 at android.os.Handler.handleCallback(Handler.java:751)
                                                                 at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                 at android.os.Looper.loop(Looper.java:154)
                                                                 at android.app.ActivityThread.main(ActivityThread.java:6119)
                                                                 at java.lang.reflect.Method.invoke(Native Method)
                                                                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
                                                                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)

```

**Comment by wangzhzh** [comment]
你可以使用Kotlin写一个简单的demo发给我，这样能加快我们的分析速度
