### ISSUE TITLE
java.lang.NoSuchMethodError: No static method aspectOf()Lcom/sensorsdata/analytics/android/sdk/aop/RadioGroupOnCheckedChangeAspectj

### ISSUE THREAD

**Issue by typ0520** [sensorsdata/sa-sdk-android#8]
os: Mac
gradle version:3.3
android-gradle-build:2.3.3

classpath 'com.sensorsdata.analytics.android:android-gradle-plugin:1.0.7'
compile 'com.sensorsdata.analytics.android:SensorsAnalyticsSDK:1.7.8'
插件也加了
apply plugin: 'com.sensorsdata.analytics.android'

编译正常，运行的时候报下面这个错误
java.lang.NoSuchMethodError: No static method aspectOf()Lcom/sensorsdata/analytics/android/sdk/aop/RadioGroupOnCheckedChangeAspectj; in class Lcom/sensorsdata/analytics/android/sdk/aop/RadioGroupOnCheckedChangeAspectj; or its super classes (declaration of 'com.sensorsdata.analytics.android.sdk.aop.RadioGroupOnCheckedChangeAspectj' appears in /data/app/com.tianxi66.zxgb-1/base.apk:classes2.dex)
                                                                       at com.dx168.zxgb.widget.BottomBarView$1.onCheckedChanged(BottomBarView.java:52)
                                                                       at android.widget.RadioGroup.setCheckedId(RadioGroup.java:174)
                                                                       at android.widget.RadioGroup.access$600(RadioGroup.java:54)
                                                                       at android.widget.RadioGroup$CheckedStateTracker.onCheckedChanged(RadioGroup.java:358)
                                                                       at android.widget.CompoundButton.setChecked(CompoundButton.java:157)
                                                                       at android.widget.CompoundButton.toggle(CompoundButton.java:113)
                                                                       at android.widget.RadioButton.toggle(RadioButton.java:78)
                                                                       at android.widget.CompoundButton.performClick(CompoundButton.java:118)
                                                                       at android.view.View$PerformClick.run(View.java:20341)
                                                                       at android.os.Handler.handleCallback(Handler.java:815)
                                                                       at android.os.Handler.dispatchMessage(Handler.java:104)
                                                                       at android.os.Looper.loop(Looper.java:224)
                                                                       at android.app.ActivityThread.main(ActivityThread.java:5911)
                                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1113)
                                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:879)

**Comment by wangzhzh** [comment]
你是我们的客户吗？

**Comment by typ0520** [comment]
是的

**Comment by wangzhzh** [comment]
具体是哪家客户？
我们可以在客户群里进行沟通，这样方便一些

**Comment by typ0520** [comment]
银科的，我没在群里

**Comment by wangzhzh** [comment]
第四步： 在 project 级别的 gradle.properties 中添加如下配置：

android.enableBuildCache=false

这一步你做了吗？

**Comment by typ0520** [comment]
我只是做测试，没有加这个，我试试看

**Comment by wangzhzh** [comment]
需要加这个

你也可以加我微信：18610277013
