### ISSUE TITLE
AppInfoUtils 特定机型 crash

### ISSUE THREAD

**Issue by bruce3x** [sensorsdata/sa-sdk-android#98]
线上用户遇到的 crash

```
java.lang.AbstractMethodError: abstract method "java.lang.CharSequence android.content.pm.PackageManager.getLabelByNubia(java.lang.String, int, android.content.pm.ApplicationInfo)"
    at android.content.pm.PackageItemInfo.loadUnsafeLabel(PackageItemInfo.java:235)
    at android.content.pm.PackageItemInfo.loadLabel(PackageItemInfo.java:214)
    at com.sensorsdata.analytics.android.sdk.util.AppInfoUtils.getAppName(AppInfoUtils.java:52)
    at com.sensorsdata.analytics.android.sdk.plugin.property.SAPresetPropertyPlugin.appendProperties(SAPresetPropertyPlugin.java:83)
    at com.sensorsdata.analytics.android.sdk.plugin.property.SAPropertyPlugin.start(SAPropertyPlugin.java:81)
    at com.sensorsdata.analytics.android.sdk.plugin.property.SensorsDataPropertyPluginManager.registerPropertyPlugin(SensorsDataPropertyPluginManager.java:67)
    at com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI.registerDefaultPropertiesPlugin(AbstractSensorsDataAPI.java:237)
    at com.sensorsdata.analytics.android.sdk.AbstractSensorsDataAPI.<init>(AbstractSensorsDataAPI.java:233)
    at com.sensorsdata.analytics.android.sdk.SensorsDataAPI.<init>(SensorsDataAPI.java:91)
    at com.sensorsdata.analytics.android.sdk.SensorsDataAPI.getInstance(SensorsDataAPI.java:147)
    at com.sensorsdata.analytics.android.sdk.SensorsDataAPI.startWithConfigOptions(SensorsDataAPI.java:131)
```

设备 nubia NX669J
系统 Android 12

sensor data sdk 6.3.1

**Comment by YueJZSensorsData** [comment]
在堆栈的最上层 `android.content.pm.PackageManager.getLabelByNubia` 这个方法出现了异常，应该是努比亚某些机型 ROM 层有问题，导致 SDK 调用有问题，这个问题 SDK 也是无能为力的

**Comment by bruce3x** [comment]
sdk 里面 try-catch 的是 `Exception`，是否可以改成 `Throwable` 这样就能把异常捕获了

![image](https://user-images.githubusercontent.com/15318754/168517473-45fd5e2e-5b19-4f1a-b44c-e71b986a2b77.png)
![image](https://user-images.githubusercontent.com/15318754/168517479-ce2e2cae-4a11-4664-a8db-d5aaeceab6c9.png)

**Comment by dengshiwei** [comment]
@bruce3x 也是一种方式吧。

**Comment by bruce3x** [comment]
那你们打算修复并更新吗？👀

**Comment by dengshiwei** [comment]
后续会考虑一下进行修复更新，时间待定。更新后我同步给你

**Comment by dengshiwei** [comment]
@bruce3x  已经优化，可以升级到最新版本使用
